services:
  - type: web
    name: diskulbre
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: CSV_PATH
        value: data/beis_masterlist.csv
    autoDeploy: true